// <auto-generated />
using DataAccessLayer;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace DataAccessLayer.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20220414061758_eklenbadbaaaaaa")]
    partial class eklenbadbaaaaaa
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.14")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("EntitiyLayer.Login.AppRole", b =>
                {
                    b.Property<int>("AppRoleID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Definition")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("AppRoleID");

                    b.ToTable("AppRoles");
                });

            modelBuilder.Entity("EntitiyLayer.Login.AppUser", b =>
                {
                    b.Property<int>("AppUserID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("AppRoleID")
                        .HasColumnType("int");

                    b.Property<string>("Password")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Username")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("AppUserID");

                    b.HasIndex("AppRoleID");

                    b.ToTable("AppUsers");
                });

            modelBuilder.Entity("EntitiyLayer.Players", b =>
                {
                    b.Property<int>("PlayersID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<double>("AST")
                        .HasColumnType("float");

                    b.Property<double>("BLK")
                        .HasColumnType("float");

                    b.Property<double>("DRB")
                        .HasColumnType("float");

                    b.Property<double>("FG")
                        .HasColumnType("float");

                    b.Property<double>("FGA")
                        .HasColumnType("float");

                    b.Property<double>("FGP")
                        .HasColumnType("float");

                    b.Property<double>("FT")
                        .HasColumnType("float");

                    b.Property<double>("FTA")
                        .HasColumnType("float");

                    b.Property<double>("FTP")
                        .HasColumnType("float");

                    b.Property<int>("Games")
                        .HasColumnType("int");

                    b.Property<int>("GamesStarted")
                        .HasColumnType("int");

                    b.Property<double>("MP")
                        .HasColumnType("float");

                    b.Property<double>("ORB")
                        .HasColumnType("float");

                    b.Property<double>("PF")
                        .HasColumnType("float");

                    b.Property<double>("PTS")
                        .HasColumnType("float");

                    b.Property<int>("PlayerJerseyNo")
                        .HasColumnType("int");

                    b.Property<string>("PlayerName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Playerimg")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Position")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("STL")
                        .HasColumnType("float");

                    b.Property<double>("TOV")
                        .HasColumnType("float");

                    b.Property<double>("TP")
                        .HasColumnType("float");

                    b.Property<double>("TPA")
                        .HasColumnType("float");

                    b.Property<double>("TPP")
                        .HasColumnType("float");

                    b.Property<double>("TRB")
                        .HasColumnType("float");

                    b.Property<int>("TeamsID")
                        .HasColumnType("int");

                    b.Property<double>("TwP")
                        .HasColumnType("float");

                    b.Property<double>("TwPA")
                        .HasColumnType("float");

                    b.Property<double>("TwPP")
                        .HasColumnType("float");

                    b.Property<double>("eFG")
                        .HasColumnType("float");

                    b.HasKey("PlayersID");

                    b.HasIndex("TeamsID");

                    b.ToTable("oyuncular");
                });

            modelBuilder.Entity("EntitiyLayer.Teams", b =>
                {
                    b.Property<int>("TeamsID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("ChCount")
                        .HasColumnType("int");

                    b.Property<string>("Conference")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Lose")
                        .HasColumnType("int");

                    b.Property<double>("OpponentPointsPerGame")
                        .HasColumnType("float");

                    b.Property<double>("PointsPerGame")
                        .HasColumnType("float");

                    b.Property<string>("TeamArena")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TeamCity")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TeamName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Win")
                        .HasColumnType("int");

                    b.Property<double>("WinLosePercentage")
                        .HasColumnType("float");

                    b.HasKey("TeamsID");

                    b.ToTable("takimlar");
                });

            modelBuilder.Entity("NbaWebApi.Login.Category", b =>
                {
                    b.Property<int>("CategoryID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Definition")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CategoryID");

                    b.ToTable("Categories");
                });

            modelBuilder.Entity("NbaWebApi.Login.Product", b =>
                {
                    b.Property<int>("ProductID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("CategoryID")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("ProductID");

                    b.HasIndex("CategoryID");

                    b.ToTable("Products");
                });

            modelBuilder.Entity("EntitiyLayer.Login.AppUser", b =>
                {
                    b.HasOne("EntitiyLayer.Login.AppRole", "AppRole")
                        .WithMany("AppUsers")
                        .HasForeignKey("AppRoleID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AppRole");
                });

            modelBuilder.Entity("EntitiyLayer.Players", b =>
                {
                    b.HasOne("EntitiyLayer.Teams", "Teams")
                        .WithMany("Players")
                        .HasForeignKey("TeamsID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Teams");
                });

            modelBuilder.Entity("NbaWebApi.Login.Product", b =>
                {
                    b.HasOne("NbaWebApi.Login.Category", "Category")
                        .WithMany("Products")
                        .HasForeignKey("CategoryID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("EntitiyLayer.Login.AppRole", b =>
                {
                    b.Navigation("AppUsers");
                });

            modelBuilder.Entity("EntitiyLayer.Teams", b =>
                {
                    b.Navigation("Players");
                });

            modelBuilder.Entity("NbaWebApi.Login.Category", b =>
                {
                    b.Navigation("Products");
                });
#pragma warning restore 612, 618
        }
    }
}
